name: FeedlyOpmlImportApplication

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GITHUB_NAME: superleeyom
  GITHUB_EMAIL: 635709492@qq.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: execute application
        run: mvn -B clean compile exec:java -Dexec.mainClass="com.leeyom.opml.app.OpmlUtils" -Dexec.args="${{ secrets.FEEDLY_TOKEN }} ${{ secrets.TG_CHAT_ID }} ${{ secrets.TG_TOKEN }}" --file pom.xml
        with:
          env:
            - name: FEEDLY_TOKEN
              value: ${{ secrets.FEEDLY_TOKEN }}
            - name: SENDER
              value: ${{ secrets.SENDER }}
            - name: TG_CHAT_ID
              value: ${{ secrets.TG_CHAT_ID }}
            - name: TG_TOKEN
              value: ${{ secrets.TG_TOKEN }}
            - name: EMAIL
              value: ${{ secrets.EMAIL }}
            - name: EMAIL_PASS
              value: ${{ secrets.EMAIL_PASS }}
            - name: EMAIL_HOST
              value: ${{ secrets.EMAIL_HOST }}
            - name: SC_KEY
              value: ${{ secrets.SC_KEY }}

      - name: update README.md
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.G_TOKEN }}
          commit-message: ":memo: update feed.opml"
          files: README.md feed.opml
          rebase: 'true'
          name: ${{ env.GITHUB_NAME }}
          email: ${{ env.GITHUB_EMAIL }}

      - name: create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.G_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          draft: false
          title: "update OPML"
          files: |
            feed.opml