name: FeedlyOpmlImportApplication

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GITHUB_NAME: 1997d12
  GITHUB_EMAIL: a13768248469@gmail.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: execute application
        run: mvn -B clean compile exec:java -Dexec.mainClass="com.leeyom.opml.app.OpmlUtils" --file pom.xml
        env:
          GITHUB_NAME: ${{ env.GITHUB_NAME }}
          FEEDLY_TOKEN: ${{ secrets.FEEDLY_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          SC_KEY: ${{ secrets.SC_KEY }}

      - name: update opml
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_EMAIL }}"
          git commit -a -m '🎉update opml' || echo "nothing to commit"
          git push || echo "nothing to push"

      - name: create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.G_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          draft: false
          title: "update OPML"
          files: |
            feed.opml
